// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: countryGPB.proto

package io.git.models.gpb;

public final class CountryProtos {
  public CountryProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CountryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.git.models.gpb.Country)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string country = 1;</code>
     */
    boolean hasCountry();
    /**
     * <code>required string country = 1;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>required string country = 1;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>required string continent = 2;</code>
     */
    boolean hasContinent();
    /**
     * <code>required string continent = 2;</code>
     */
    java.lang.String getContinent();
    /**
     * <code>required string continent = 2;</code>
     */
    com.google.protobuf.ByteString
        getContinentBytes();

    /**
     * <code>required string capital = 3;</code>
     */
    boolean hasCapital();
    /**
     * <code>required string capital = 3;</code>
     */
    java.lang.String getCapital();
    /**
     * <code>required string capital = 3;</code>
     */
    com.google.protobuf.ByteString
        getCapitalBytes();

    /**
     * <code>required string locale = 4;</code>
     */
    boolean hasLocale();
    /**
     * <code>required string locale = 4;</code>
     */
    java.lang.String getLocale();
    /**
     * <code>required string locale = 4;</code>
     */
    com.google.protobuf.ByteString
        getLocaleBytes();
  }
  /**
   * Protobuf type {@code io.git.models.gpb.Country}
   */
  public  static final class Country extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.git.models.gpb.Country)
      CountryOrBuilder {
    // Use Country.newBuilder() to construct.
    private Country(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Country() {
      country_ = "";
      continent_ = "";
      capital_ = "";
      locale_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Country(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              country_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              continent_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              capital_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              locale_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.git.models.gpb.CountryProtos.internal_static_io_git_models_gpb_Country_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.git.models.gpb.CountryProtos.internal_static_io_git_models_gpb_Country_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.git.models.gpb.CountryProtos.Country.class, io.git.models.gpb.CountryProtos.Country.Builder.class);
    }

    private int bitField0_;
    public static final int COUNTRY_FIELD_NUMBER = 1;
    private volatile java.lang.Object country_;
    /**
     * <code>required string country = 1;</code>
     */
    public boolean hasCountry() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string country = 1;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          country_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string country = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTINENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object continent_;
    /**
     * <code>required string continent = 2;</code>
     */
    public boolean hasContinent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string continent = 2;</code>
     */
    public java.lang.String getContinent() {
      java.lang.Object ref = continent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          continent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string continent = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContinentBytes() {
      java.lang.Object ref = continent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        continent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAPITAL_FIELD_NUMBER = 3;
    private volatile java.lang.Object capital_;
    /**
     * <code>required string capital = 3;</code>
     */
    public boolean hasCapital() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string capital = 3;</code>
     */
    public java.lang.String getCapital() {
      java.lang.Object ref = capital_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          capital_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string capital = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCapitalBytes() {
      java.lang.Object ref = capital_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        capital_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALE_FIELD_NUMBER = 4;
    private volatile java.lang.Object locale_;
    /**
     * <code>required string locale = 4;</code>
     */
    public boolean hasLocale() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string locale = 4;</code>
     */
    public java.lang.String getLocale() {
      java.lang.Object ref = locale_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          locale_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string locale = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLocaleBytes() {
      java.lang.Object ref = locale_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCountry()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContinent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCapital()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocale()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, country_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, continent_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, capital_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, locale_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, country_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, continent_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, capital_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, locale_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.git.models.gpb.CountryProtos.Country)) {
        return super.equals(obj);
      }
      io.git.models.gpb.CountryProtos.Country other = (io.git.models.gpb.CountryProtos.Country) obj;

      boolean result = true;
      result = result && (hasCountry() == other.hasCountry());
      if (hasCountry()) {
        result = result && getCountry()
            .equals(other.getCountry());
      }
      result = result && (hasContinent() == other.hasContinent());
      if (hasContinent()) {
        result = result && getContinent()
            .equals(other.getContinent());
      }
      result = result && (hasCapital() == other.hasCapital());
      if (hasCapital()) {
        result = result && getCapital()
            .equals(other.getCapital());
      }
      result = result && (hasLocale() == other.hasLocale());
      if (hasLocale()) {
        result = result && getLocale()
            .equals(other.getLocale());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCountry()) {
        hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
        hash = (53 * hash) + getCountry().hashCode();
      }
      if (hasContinent()) {
        hash = (37 * hash) + CONTINENT_FIELD_NUMBER;
        hash = (53 * hash) + getContinent().hashCode();
      }
      if (hasCapital()) {
        hash = (37 * hash) + CAPITAL_FIELD_NUMBER;
        hash = (53 * hash) + getCapital().hashCode();
      }
      if (hasLocale()) {
        hash = (37 * hash) + LOCALE_FIELD_NUMBER;
        hash = (53 * hash) + getLocale().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.git.models.gpb.CountryProtos.Country parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.git.models.gpb.CountryProtos.Country parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.git.models.gpb.CountryProtos.Country parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.git.models.gpb.CountryProtos.Country parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.git.models.gpb.CountryProtos.Country parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.git.models.gpb.CountryProtos.Country parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.git.models.gpb.CountryProtos.Country parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.git.models.gpb.CountryProtos.Country parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.git.models.gpb.CountryProtos.Country parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.git.models.gpb.CountryProtos.Country parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.git.models.gpb.CountryProtos.Country prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.git.models.gpb.Country}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.git.models.gpb.Country)
        io.git.models.gpb.CountryProtos.CountryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.git.models.gpb.CountryProtos.internal_static_io_git_models_gpb_Country_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.git.models.gpb.CountryProtos.internal_static_io_git_models_gpb_Country_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.git.models.gpb.CountryProtos.Country.class, io.git.models.gpb.CountryProtos.Country.Builder.class);
      }

      // Construct using io.git.models.gpb.CountryProtos.Country.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        country_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        continent_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        capital_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        locale_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.git.models.gpb.CountryProtos.internal_static_io_git_models_gpb_Country_descriptor;
      }

      public io.git.models.gpb.CountryProtos.Country getDefaultInstanceForType() {
        return io.git.models.gpb.CountryProtos.Country.getDefaultInstance();
      }

      public io.git.models.gpb.CountryProtos.Country build() {
        io.git.models.gpb.CountryProtos.Country result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.git.models.gpb.CountryProtos.Country buildPartial() {
        io.git.models.gpb.CountryProtos.Country result = new io.git.models.gpb.CountryProtos.Country(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.country_ = country_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.continent_ = continent_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.capital_ = capital_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.locale_ = locale_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.git.models.gpb.CountryProtos.Country) {
          return mergeFrom((io.git.models.gpb.CountryProtos.Country)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.git.models.gpb.CountryProtos.Country other) {
        if (other == io.git.models.gpb.CountryProtos.Country.getDefaultInstance()) return this;
        if (other.hasCountry()) {
          bitField0_ |= 0x00000001;
          country_ = other.country_;
          onChanged();
        }
        if (other.hasContinent()) {
          bitField0_ |= 0x00000002;
          continent_ = other.continent_;
          onChanged();
        }
        if (other.hasCapital()) {
          bitField0_ |= 0x00000004;
          capital_ = other.capital_;
          onChanged();
        }
        if (other.hasLocale()) {
          bitField0_ |= 0x00000008;
          locale_ = other.locale_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCountry()) {
          return false;
        }
        if (!hasContinent()) {
          return false;
        }
        if (!hasCapital()) {
          return false;
        }
        if (!hasLocale()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.git.models.gpb.CountryProtos.Country parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.git.models.gpb.CountryProtos.Country) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object country_ = "";
      /**
       * <code>required string country = 1;</code>
       */
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string country = 1;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            country_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string country = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string country = 1;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string country = 1;</code>
       */
      public Builder clearCountry() {
        bitField0_ = (bitField0_ & ~0x00000001);
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>required string country = 1;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        country_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object continent_ = "";
      /**
       * <code>required string continent = 2;</code>
       */
      public boolean hasContinent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string continent = 2;</code>
       */
      public java.lang.String getContinent() {
        java.lang.Object ref = continent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            continent_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string continent = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContinentBytes() {
        java.lang.Object ref = continent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          continent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string continent = 2;</code>
       */
      public Builder setContinent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        continent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string continent = 2;</code>
       */
      public Builder clearContinent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        continent_ = getDefaultInstance().getContinent();
        onChanged();
        return this;
      }
      /**
       * <code>required string continent = 2;</code>
       */
      public Builder setContinentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        continent_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object capital_ = "";
      /**
       * <code>required string capital = 3;</code>
       */
      public boolean hasCapital() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string capital = 3;</code>
       */
      public java.lang.String getCapital() {
        java.lang.Object ref = capital_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            capital_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string capital = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCapitalBytes() {
        java.lang.Object ref = capital_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          capital_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string capital = 3;</code>
       */
      public Builder setCapital(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        capital_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string capital = 3;</code>
       */
      public Builder clearCapital() {
        bitField0_ = (bitField0_ & ~0x00000004);
        capital_ = getDefaultInstance().getCapital();
        onChanged();
        return this;
      }
      /**
       * <code>required string capital = 3;</code>
       */
      public Builder setCapitalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        capital_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object locale_ = "";
      /**
       * <code>required string locale = 4;</code>
       */
      public boolean hasLocale() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string locale = 4;</code>
       */
      public java.lang.String getLocale() {
        java.lang.Object ref = locale_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            locale_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string locale = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLocaleBytes() {
        java.lang.Object ref = locale_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locale_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string locale = 4;</code>
       */
      public Builder setLocale(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        locale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string locale = 4;</code>
       */
      public Builder clearLocale() {
        bitField0_ = (bitField0_ & ~0x00000008);
        locale_ = getDefaultInstance().getLocale();
        onChanged();
        return this;
      }
      /**
       * <code>required string locale = 4;</code>
       */
      public Builder setLocaleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        locale_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.git.models.gpb.Country)
    }

    // @@protoc_insertion_point(class_scope:io.git.models.gpb.Country)
    private static final io.git.models.gpb.CountryProtos.Country DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.git.models.gpb.CountryProtos.Country();
    }

    public static io.git.models.gpb.CountryProtos.Country getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Country>
        PARSER = new com.google.protobuf.AbstractParser<Country>() {
      public Country parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Country(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Country> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Country> getParserForType() {
      return PARSER;
    }

    public io.git.models.gpb.CountryProtos.Country getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_git_models_gpb_Country_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_git_models_gpb_Country_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020countryGPB.proto\022\021io.git.models.gpb\"N\n" +
      "\007Country\022\017\n\007country\030\001 \002(\t\022\021\n\tcontinent\030\002" +
      " \002(\t\022\017\n\007capital\030\003 \002(\t\022\016\n\006locale\030\004 \002(\tB\"\n" +
      "\021io.git.models.gpbB\rCountryProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_git_models_gpb_Country_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_git_models_gpb_Country_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_git_models_gpb_Country_descriptor,
        new java.lang.String[] { "Country", "Continent", "Capital", "Locale", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
